# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd45b8f919e44f2c53b8786b7b9923ad963150387774d0da9c93b9735f46474d31ebe4853eb0e28a1a7eb62c38d56fcef30b775153a1a6b6db37ef2af5972c34

test:
  secret_key_base: e4ac97a07ba2c9716cd988d1783c2e183eb3bab56874d9b149132d924f9678f29e5c7fc239123c05e0ab15f3cba4b146ba06849f316f9bb95cdfabc7973a503b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
